"""fix coordinator dashborad schema

Revision ID: 0a5f41a94750
Revises: 71ae2c9ae1a1
Create Date: 2026-03-07 17:51:43.456287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a5f41a94750'
down_revision: Union[str, Sequence[str], None] = '71ae2c9ae1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.add_column('application_documents', sa.Column('document_label', sa.String(), nullable=False))
    op.add_column('application_documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('application_documents', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('application_documents', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('application_documents', sa.Column('review_notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'application_documents', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('application_documents', 'rejection_reason')
    op.add_column('audit_logs', sa.Column('user_role', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_logs', 'old_status')
    op.drop_column('audit_logs', 'new_status')
    op.drop_column('audit_logs', 'user_agent')
    op.alter_column('calls_for_applicants', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('calls_for_applicants', 'eligibility_criteria',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('calls_for_applicants', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('calls_for_applicants_reference_number_key'), 'calls_for_applicants', type_='unique')
    op.drop_index(op.f('ix_calls_for_applicants_deadline'), table_name='calls_for_applicants')
    op.create_index(op.f('ix_calls_for_applicants_reference_number'), 'calls_for_applicants', ['reference_number'], unique=True)
    op.drop_constraint(op.f('calls_for_applicants_created_by_id_fkey'), 'calls_for_applicants', type_='foreignkey')
    op.create_foreign_key(None, 'calls_for_applicants', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.add_column('company_applications', sa.Column('proposed_employee_count', sa.Integer(), nullable=False))
    op.add_column('company_applications', sa.Column('coordinator_id', sa.Integer(), nullable=True))
    op.add_column('company_applications', sa.Column('decision_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('company_applications', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.alter_column('company_applications', 'motivation_letter',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company_applications', 'decision_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company_applications', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_foreign_key(None, 'company_applications', 'users', ['coordinator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('company_applications', 'created_at')
    op.drop_column('company_applications', 'additional_notes')
    op.drop_column('company_applications', 'coordinator_decision')
    op.drop_column('company_applications', 'reviewed_at')
    op.add_column('employee_profiles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee_profiles', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('employee_submission_documents', sa.Column('document_label', sa.String(), nullable=False))
    op.add_column('employee_submission_documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('employee_submission_documents', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('employee_submission_documents', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('employee_submission_documents', sa.Column('review_notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'employee_submission_documents', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employee_submission_documents', 'rejection_reason')
    op.add_column('employee_submissions', sa.Column('company_application_id', sa.Integer(), nullable=False))
    op.add_column('employee_submissions', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('employee_submissions', sa.Column('review_notes', sa.String(), nullable=True))
    op.drop_index(op.f('ix_employee_submissions_application_id'), table_name='employee_submissions')
    op.drop_constraint(op.f('uq_application_employee_submission'), 'employee_submissions', type_='unique')
    op.create_unique_constraint('uq_application_employee_submission', 'employee_submissions', ['company_application_id', 'employee_id'])
    op.create_index(op.f('ix_employee_submissions_company_application_id'), 'employee_submissions', ['company_application_id'], unique=False)
    op.drop_constraint(op.f('employee_submissions_application_id_fkey'), 'employee_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'employee_submissions', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employee_submissions', 'company_applications', ['company_application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employee_submissions', 'application_id')
    op.drop_column('employee_submissions', 'coordinator_notes')
    op.drop_column('employee_submissions', 'submitted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_submissions', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employee_submissions', sa.Column('coordinator_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employee_submissions', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_submissions', type_='foreignkey')
    op.drop_constraint(None, 'employee_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('employee_submissions_application_id_fkey'), 'employee_submissions', 'company_applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_submissions_company_application_id'), table_name='employee_submissions')
    op.drop_constraint('uq_application_employee_submission', 'employee_submissions', type_='unique')
    op.create_unique_constraint(op.f('uq_application_employee_submission'), 'employee_submissions', ['application_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_employee_submissions_application_id'), 'employee_submissions', ['application_id'], unique=False)
    op.drop_column('employee_submissions', 'review_notes')
    op.drop_column('employee_submissions', 'reviewed_by_id')
    op.drop_column('employee_submissions', 'company_application_id')
    op.add_column('employee_submission_documents', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_submission_documents', type_='foreignkey')
    op.drop_column('employee_submission_documents', 'review_notes')
    op.drop_column('employee_submission_documents', 'reviewed_by_id')
    op.drop_column('employee_submission_documents', 'mime_type')
    op.drop_column('employee_submission_documents', 'file_size')
    op.drop_column('employee_submission_documents', 'document_label')
    op.drop_constraint(None, 'employee_profiles', type_='foreignkey')
    op.drop_column('employee_profiles', 'company_id')
    op.add_column('company_applications', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('company_applications', sa.Column('coordinator_decision', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('company_applications', sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('company_applications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company_applications', type_='foreignkey')
    op.alter_column('company_applications', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('company_applications', 'decision_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('company_applications', 'motivation_letter',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('company_applications', 'rejection_reason')
    op.drop_column('company_applications', 'decision_date')
    op.drop_column('company_applications', 'coordinator_id')
    op.drop_column('company_applications', 'proposed_employee_count')
    op.drop_constraint(None, 'calls_for_applicants', type_='foreignkey')
    op.create_foreign_key(op.f('calls_for_applicants_created_by_id_fkey'), 'calls_for_applicants', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_calls_for_applicants_reference_number'), table_name='calls_for_applicants')
    op.create_index(op.f('ix_calls_for_applicants_deadline'), 'calls_for_applicants', ['application_deadline'], unique=False)
    op.create_unique_constraint(op.f('calls_for_applicants_reference_number_key'), 'calls_for_applicants', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('calls_for_applicants', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('calls_for_applicants', 'eligibility_criteria',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('calls_for_applicants', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('old_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.alter_column('audit_logs', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'user_role')
    op.add_column('application_documents', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_documents', type_='foreignkey')
    op.drop_column('application_documents', 'review_notes')
    op.drop_column('application_documents', 'reviewed_by_id')
    op.drop_column('application_documents', 'mime_type')
    op.drop_column('application_documents', 'file_size')
    op.drop_column('application_documents', 'document_label')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('employees_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey'))
    )
    # ### end Alembic commands ###
