"""add cohorts

Revision ID: 52889f6d0e05
Revises: 842cae30c263
Create Date: 2026-03-16 22:53:12.730322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52889f6d0e05'
down_revision: Union[str, Sequence[str], None] = '842cae30c263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('training_start_date', sa.Date(), nullable=False),
    sa.Column('training_end_date', sa.Date(), nullable=False),
    sa.Column('daily_start_hour', sa.Time(), nullable=False),
    sa.Column('daily_end_hour', sa.Time(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls_for_applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_call_id'), 'cohorts', ['call_id'], unique=False)
    op.create_index(op.f('ix_cohorts_course_id'), 'cohorts', ['course_id'], unique=False)
    op.create_index(op.f('ix_cohorts_name'), 'cohorts', ['name'], unique=False)
    op.create_table('cohort_professor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'professor_id', name='uq_cohort_professor_assignment')
    )
    op.create_index(op.f('ix_cohort_professor_assignments_cohort_id'), 'cohort_professor_assignments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_professor_assignments_professor_id'), 'cohort_professor_assignments', ['professor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_professor_assignments_professor_id'), table_name='cohort_professor_assignments')
    op.drop_index(op.f('ix_cohort_professor_assignments_cohort_id'), table_name='cohort_professor_assignments')
    op.drop_table('cohort_professor_assignments')
    op.drop_index(op.f('ix_cohorts_name'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_course_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_call_id'), table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
