"""course_availability

Revision ID: 528fb39cac70
Revises: f7a8b9c0d1e2
Create Date: 2026-01-25 17:23:30.519843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '528fb39cac70'
down_revision: Union[str, Sequence[str], None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('min_seats', sa.Integer(), nullable=False),
    sa.Column('reserved_seats', sa.Integer(), nullable=False),
    sa.Column('booking_deadline', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending_review', 'confirmed', 'cancelled', name='availability_slot_status', create_constraint=True), server_default='open', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_availability_course_id'), 'course_availability', ['course_id'], unique=False)
    op.create_table('company_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('availability_slot_id', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reserved', 'confirmed', 'cancelled', name='booking_status', create_constraint=True), server_default='reserved', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('staff_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['course_availability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'availability_slot_id', name='uq_company_slot_booking')
    )
    op.create_index(op.f('ix_company_bookings_availability_slot_id'), 'company_bookings', ['availability_slot_id'], unique=False)
    op.create_index(op.f('ix_company_bookings_company_id'), 'company_bookings', ['company_id'], unique=False)
    op.add_column('courses', sa.Column('sector', sa.String(), nullable=True))
    op.create_index(op.f('ix_courses_sector'), 'courses', ['sector'], unique=False)
    op.drop_column('courses', 'schedule')
    op.drop_column('courses', 'start_date')
    op.drop_column('courses', 'end_date')
    op.drop_index(op.f('ix_newsletter_subscriptions_email'), table_name='newsletter_subscriptions')
    op.create_index(op.f('ix_newsletter_subscriptions_email'), 'newsletter_subscriptions', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subscriptions_email'), table_name='newsletter_subscriptions')
    op.create_index(op.f('ix_newsletter_subscriptions_email'), 'newsletter_subscriptions', ['email'], unique=False)
    op.add_column('courses', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_courses_sector'), table_name='courses')
    op.drop_column('courses', 'sector')
    op.drop_index(op.f('ix_company_bookings_company_id'), table_name='company_bookings')
    op.drop_index(op.f('ix_company_bookings_availability_slot_id'), table_name='company_bookings')
    op.drop_table('company_bookings')
    op.drop_index(op.f('ix_course_availability_course_id'), table_name='course_availability')
    op.drop_table('course_availability')
    # ### end Alembic commands ###
