"""Added cohort attendance data model

Revision ID: 7b659a00fa51
Revises: b404a9327891
Create Date: 2026-03-25 15:05:22.071939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b659a00fa51'
down_revision: Union[str, Sequence[str], None] = 'b404a9327891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_session_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', name='attendance_status_type', create_constraint=True), server_default='present', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('marked_by_id', sa.Integer(), nullable=True),
    sa.Column('marked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['cohort_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'employee_id', name='uq_cohort_session_employee_attendance')
    )
    op.create_index(op.f('ix_cohort_session_attendance_employee_id'), 'cohort_session_attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_cohort_session_attendance_session_id'), 'cohort_session_attendance', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_session_attendance_session_id'), table_name='cohort_session_attendance')
    op.drop_index(op.f('ix_cohort_session_attendance_employee_id'), table_name='cohort_session_attendance')
    op.drop_table('cohort_session_attendance')
    # ### end Alembic commands ###
