"""add invitations

Revision ID: 842cae30c263
Revises: 0a5f41a94750
Create Date: 2026-03-08 14:24:11.471829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842cae30c263'
down_revision: Union[str, Sequence[str], None] = '0a5f41a94750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['company_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_invitations_application_id'), 'company_invitations', ['application_id'], unique=True)
    op.create_index(op.f('ix_company_invitations_token'), 'company_invitations', ['token'], unique=True)
    op.create_table('employee_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_invitation_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('employee_email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['company_invitation_id'], ['company_invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_invitations_company_invitation_id'), 'employee_invitations', ['company_invitation_id'], unique=False)
    op.create_index(op.f('ix_employee_invitations_employee_email'), 'employee_invitations', ['employee_email'], unique=False)
    op.create_index(op.f('ix_employee_invitations_token'), 'employee_invitations', ['token'], unique=True)
    op.add_column('news', sa.Column('call_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('attachment_path', sa.String(), nullable=True))
    op.create_foreign_key(None, 'news', 'calls_for_applicants', ['call_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'attachment_path')
    op.drop_column('news', 'call_id')
    op.drop_index(op.f('ix_employee_invitations_token'), table_name='employee_invitations')
    op.drop_index(op.f('ix_employee_invitations_employee_email'), table_name='employee_invitations')
    op.drop_index(op.f('ix_employee_invitations_company_invitation_id'), table_name='employee_invitations')
    op.drop_table('employee_invitations')
    op.drop_index(op.f('ix_company_invitations_token'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_application_id'), table_name='company_invitations')
    op.drop_table('company_invitations')
    # ### end Alembic commands ###
