"""add cohort session

Revision ID: b404a9327891
Revises: 52889f6d0e05
Create Date: 2026-03-19 13:18:55.040110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b404a9327891'
down_revision: Union[str, Sequence[str], None] = '52889f6d0e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_sessions_cohort_id'), 'cohort_sessions', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_sessions_professor_id'), 'cohort_sessions', ['professor_id'], unique=False)
    op.create_index(op.f('ix_cohort_sessions_session_date'), 'cohort_sessions', ['session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_sessions_session_date'), table_name='cohort_sessions')
    op.drop_index(op.f('ix_cohort_sessions_professor_id'), table_name='cohort_sessions')
    op.drop_index(op.f('ix_cohort_sessions_cohort_id'), table_name='cohort_sessions')
    op.drop_table('cohort_sessions')
    # ### end Alembic commands ###
